defaults :
  - physicsnemo_default
  - arch:
      - fully_connected
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

scheduler:
  decay_rate: 0.9
  decay_steps: 5000

training:
 rec_validation_freq: 1000
 rec_monitor_freq: 1000
 rec_constraint_freq: 50000
 max_steps: 20000

batch_size:
 LB: 256
 RB: 256
 interior: 1024

graph:
 func_arch: true
